# Font configuration
font:
  normal:
    family: Inconsolata Nerd Font
    style: Regular
  bold:
    family: Inconsolata Nerd Font
    style: Bold
  italic:
    family: Inconsolata Nerd Font
    style: Italic
  bold_italic:
    family: Inconsolata Nerd Font
    style: Bold Italic
  size: 12.0

# Base16 Default Dark - alacritty color config
# Chris Kempson (http://chriskempson.com)
colors:
  # Default colors
  primary:
    background: '0x181818'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x181818'
    cursor: '0xd8d8d8'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xdc9656'
    green:   '0x282828'
    yellow:  '0x383838'
    blue:    '0xb8b8b8'
    magenta: '0xe8e8e8'
    cyan:    '0xa16946'
    white:   '0xf8f8f8'

# Base16 Solarized Light - alacritty color config
# Ethan Schoonover (modified by aramisgithub)
#colors:
#  # Default colors
#  primary:
#    background: '0xfdf6e3'
#    foreground: '0x586e75'
#
#  # Colors the cursor will use if `custom_cursor_colors` is true
#  cursor:
#    text: '0xfdf6e3'
#    cursor: '0x586e75'
#
#  # Normal colors
#  normal:
#    black:   '0xfdf6e3'
#    red:     '0xdc322f'
#    green:   '0x859900'
#    yellow:  '0xb58900'
#    blue:    '0x268bd2'
#    magenta: '0x6c71c4'
#    cyan:    '0x2aa198'
#    white:   '0x586e75'
#
#  # Bright colors
#  bright:
#    black:   '0x839496'
#    red:     '0xcb4b16'
#    green:   '0xeee8d5'
#    yellow:  '0x93a1a1'
#    blue:    '0x657b83'
#    magenta: '0x073642'
#    cyan:    '0xd33682'
#    white:   '0x002b36'

draw_bold_text_with_bright_colors: false


bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0
