[".config/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"  # Weekly update
[".config/tmux/plugins/tmux-sensible"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-sensible.git"
    refreshPeriod = "168h"  # Weekly update
[".config/tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect.git"
    refreshPeriod = "168h"  # Weekly update
[".config/tmux/plugins/tmux-continuum"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-continuum.git"
    refreshPeriod = "168h"  # Weekly update
[".config/tmux/plugins/tmux-yank"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-yank.git"
    refreshPeriod = "168h"  # Weekly update
[".config/tmux/plugins/tmux-powerline"]
    type = "git-repo"
    url = "https://github.com/erikw/tmux-powerline.git"
    refreshPeriod = "168h"  # Weekly update
