[user]
name = "Kyle Wenholz"
email = "kyle@krwenholz.com"

[revsets]
# Show commits that are not in `main@origin`
log = "main@origin.."
# Default is 'present(@) | ancestors(immutable_heads().., 2) | present(trunk())'