# Don't print a newline at the start of the prompt
add_newline = false

# Default format from: https://starship.rs/config/#default-prompt-format
format = """$status\
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$cmd_duration\
$custom\
$line_break\
$lua\
$jobs\
$battery\
$time\
$character"""

# One-line prompt
[line_break]
disabled = false

# The character stays the same!
[character]
# Careful that these are simple chars, otherwise VSCode might render them improperly, breaking
# line-wrapping.
success_symbol = "[>>>](green)"
error_symbol = "[>>>](red)"
vicmd_symbol = "[>>>](bg:white fg:green)"

[status]
disabled = false
symbol = ""
style = "yellow"

[directory]
style = "purple"
truncate_to_repo = false

[git_branch]
format = "[\\[$symbol$branch\\]]($style) "
symbol = ""
style = "green"

[git_status]
format = "([$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind]($style) )"
ahead = "[⇡${count}](7)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](7)"
behind = "[⇣${count}](7)"
modified = "[!](red)"
deleted = "[x](red)"
untracked = "[?](yellow)"
staged = "[+](yellow)"
renamed = ""
style = "green"

[cmd_duration]
disabled = false

[aws]
disabled = true

[jobs]
disabled = true

[nix_shell]
disabled = true

[hostname]
format = "[$hostname]($style):"
style = "cyan"

[username]
format = "[$user@]($style)"
style_user = "cyan"

[php]
disabled = true

[ruby]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[terraform]
disabled = true

[elm]
disabled = true

