# Don't print a newline at the start of the prompt
add_newline = false

# Default format from: https://starship.rs/config/#default-prompt-format
format = """$status\
$username\
$hostname\
$shlvl\
$directory\
$cmd_duration\
$custom\
$line_break\
$character"""

# One-line prompt
[line_break]
disabled = false

# The character stays the same!
[character]
# Careful that these are simple chars, otherwise VSCode might render them improperly, breaking
# line-wrapping.
success_symbol = "[-->](green)"
error_symbol = "[-->](red)"
vicmd_symbol = "[-->](bg:white fg:green)"

# https://starship.rs/config/#example-81
# [custom.foo]
# command = 'echo foo' # shows output of command
# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$HOME" = "$PWD" '''
# format = ' transcending [$output]($style)'

[status]
disabled = false
symbol = ""
style = "yellow"

[directory]
style = "purple"
truncate_to_repo = false
format = '[$path]($style) '
truncation_length = 8

[cmd_duration]
disabled = false
min_time = 500 # milliseconds
format = 'took [$duration]($style) '

[hostname]
format = "[$hostname]($style):"
style = "cyan"

[username]
format = "[$user@]($style)"
style_user = "cyan"