[user]
name = "Kyle Wenholz"
email = "kyle@krwenholz.com"

[[--scope]]
--when.repositories = ["/workspaces/fay-service", "/workspaces/fay-ui"]
[--scope.user]
email = "krwenholz@faynutrition.com"

[ui]
editor = "nvim"

[revsets]
# Show commits that are not in `main@origin`
log = "main@origin.."
# Default is 'present(@) | ancestors(immutable_heads().., 2) | present(trunk())'

[revset-aliases]
'MINE' = '(trunk()..(visible_heads() & mine()))'

[git]
auto-local-bookmark = true

[aliases]
# See https://jj-vcs.github.io/jj/latest/config/#aliases 
pre-commit = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff --from @ --to main --name-only --no-pager | xargs pre-commit run --files",
]
