[user]
name = "Kyle Wenholz"
email = "kyle@krwenholz.com"

[[--scope]]
--when.repositories = ["/workspaces/fay-service", "/workspaces/fay-ui"]
[--scope.user]
email = "krwenholz@faynutrition.com"

[[--scope]]
--when.repositories = ["/Users/kylewenholz/Source/maintainx/*"]
[--scope.user]
email = "kyle.wenholz@getmaintainx.com"
name = "Kyle Wenholz"

[ui]
editor = "nvim"

[revsets]
# Show commits that are not in trunk (auto-detects main/master/trunk on origin)
log = "trunk().."
# Default is 'present(@) | ancestors(immutable_heads().., 2) | present(trunk())'

[revset-aliases]
'MINE' = '(trunk()..(visible_heads() & mine()))'

[aliases]
# See https://jj-vcs.github.io/jj/latest/config/#aliases 
pre-commit = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff --from @ --to 'trunk()' --name-only --no-pager | xargs pre-commit run --files",
]

[remotes.origin]
auto-track-bookmarks = "*"
